services:
  caddy-reverse-proxy:
    image: caddy/caddy:2.11.4-alpine
    ports:
      - "8295:8295"
    networks:
      - brave-sync
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - web
  web:
    image: ghcr.io/devloberto/brave-sync-web:latest
    # caddy takes care of in- and outbound traffic
    # ports:
    #  - "8295:8295"
    networks:
      - brave-sync
    environment:
      - PPROF_ENABLED=true
      - SENTRY_DSN
      - ENV=local
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=GOSYNC
      - AWS_SECRET_ACCESS_KEY=GOSYNC
      - AWS_REGION=us-west-2
      - AWS_ENDPOINT=http://dynamo:8000
      - TABLE_NAME=client-entity-dev
      - REDIS_URL=redis:6379
  dynamo:
    image: ghcr.io/devloberto/brave-sync-dynamo:latest
    ports:
      - "8000:8000"
    networks:
      - brave-sync
    volumes:
      - "./mnt/dynamo:/db"
  redis:
    image: redis:6.2.22-alpine3.21
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - brave-sync
    volumes:
      - "./mnt/redis:/data"

networks:
  brave-sync:
    driver: bridge
